# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f00bf1f3435402c122b2e71551f724328ccf71b0e56cd6b59d98e52d7fbacfc50706db66f7ae366a55a552d912196541e1330a2ff29a00600907cd806c3e5154

test:
  secret_key_base: c66138ff8449229020fb06ac82b570b23e143556a6fee2d94041022d84a4d5c17f471430d1d4bb7c5a3298acecec637c9d2e637fe1f9c7f6eaf9bf96db2e5264

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
